"""Train LibreYOLO26-nano on COCO person class only for 100 epochs, using SiLU activations and 640x640 resolution.
"""

import argparse
import json
import logging
import os
import re
import shutil
from pathlib import Path

import torch
from libreyolo import LibreYOLO26

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logging.getLogger("libreyolo").setLevel(logging.INFO)


def _run_suffix_int(name: str) -> int:
    """Extract numeric suffix from exp dir name (e.g. 'yolo26_silu_exp9' → 9, 'yolo26_silu_exp' → 1)."""
    m = re.search(r"(\d+)$", name)
    return int(m.group(1)) if m else 1


# ── Config ────────────────────────────────────────────────────────────────────
COCO_ROOT = "/home/bence/coco-2017"
PERSON_CATEGORY_ID = 1   # COCO category_id for 'person'
NC = 1
EPOCHS = 100
IMGSZ = 640
BATCH = 32


# ── Filter helpers ────────────────────────────────────────────────────────────

def _filter_coco_json(src_json: str, dst_json: str, bg_ratio: float = 0.0) -> None:
    """Write a COCO JSON containing only 'person' (category_id=1) annotations.

    Optionally includes background images containing no 'person' annotations
    based on bg_ratio.
    """
    if os.path.exists(dst_json):
        print(f"[INFO] Filtered JSON already exists, skipping: {dst_json}")
        return

    print(f"[INFO] Filtering {src_json} → {dst_json} (person only, bg_ratio={bg_ratio}) …")
    with open(src_json) as f:
        coco = json.load(f)

    person_cat = [c for c in coco["categories"] if c["id"] == PERSON_CATEGORY_ID]
    assert person_cat, "Person category not found in COCO JSON"

    person_anns = [a for a in coco["annotations"]
                   if a["category_id"] == PERSON_CATEGORY_ID]
    person_img_ids = {a["image_id"] for a in person_anns}
    person_imgs = [img for img in coco["images"]
                   if img["id"] in person_img_ids]

    if bg_ratio > 0.0:
        bg_imgs = [img for img in coco["images"] if img["id"] not in person_img_ids]
        n_bg = int(len(person_imgs) * bg_ratio / (1.0 - bg_ratio))
        bg_imgs = sorted(bg_imgs, key=lambda x: x["id"])
        import random
        rng = random.Random(42)
        bg_sample = rng.sample(bg_imgs, min(n_bg, len(bg_imgs)))
        person_imgs.extend(bg_sample)

    filtered = {
        "info": coco.get("info", {}),
        "licenses": coco.get("licenses", []),
        "images": person_imgs,
        "annotations": person_anns,
        "categories": person_cat,
    }

    tmp = dst_json + ".tmp"
    with open(tmp, "w") as f:
        json.dump(filtered, f)
    os.replace(tmp, dst_json)
    print(f"[INFO] Wrote {len(person_imgs)} images, {len(person_anns)} annotations.")


def _write_yaml(path: str, train_ann: str, val_ann: str) -> None:
    """Write a dataset YAML pointing at the filtered annotation JSONs."""
    content = f"""\
# Person-only COCO 2017 (generated by verify_training_nano_silu.py)
path: {COCO_ROOT}
train: train2017
val: val2017
train_annotation_file: {train_ann}
val_annotation_file: {val_ann}

nc: 1

names:
  0: person
"""
    with open(path, "w") as f:
        f.write(content)
    print(f"[INFO] Wrote dataset YAML: {path}")


# ── Model ─────────────────────────────────────────────────────────────────────
# Parse arguments
parser = argparse.ArgumentParser(description="Train LibreYOLO26-nano on COCO person class at 640x640 with SiLU.")
parser.add_argument("--resume", action="store_true", help="Resume from the latest checkpoint if available")
parser.add_argument("--bg-ratio", type=float, default=0.1, help="Ratio of background images (no people) in dataset")
args = parser.parse_args()

# ── Prepare filtered data ─────────────────────────────────────────────────────
ann_dir = os.path.join(COCO_ROOT, "annotations")
train_ann_src = os.path.join(ann_dir, "instances_train2017.json")
val_ann_src = os.path.join(ann_dir, "instances_val2017.json")

suffix = f"_person_bg{args.bg_ratio}" if args.bg_ratio > 0.0 else "_person"
train_ann_person = os.path.join(ann_dir, f"instances_train2017{suffix}.json")
val_ann_person = os.path.join(ann_dir, f"instances_val2017{suffix}.json")

_filter_coco_json(train_ann_src, train_ann_person, bg_ratio=args.bg_ratio)
_filter_coco_json(val_ann_src, val_ann_person, bg_ratio=args.bg_ratio)

yaml_path = os.path.join(os.path.dirname(__file__), "coco_person.yaml")
_write_yaml(yaml_path, train_ann_person, val_ann_person)

# Determine run directory and resume state
RUN_DIR_NAME = "yolo26_nano_silu_exp"
project_dir = Path("runs/train")
last_ckpt: Path | None = None

# Find the latest run directory with a last.pt checkpoint
if args.resume and project_dir.exists():
    candidates = sorted(
        [d for d in project_dir.iterdir() if d.name.startswith(RUN_DIR_NAME) and d.is_dir()],
        key=lambda d: _run_suffix_int(d.name),
        reverse=True,
    )
    for candidate in candidates:
        ckpt = candidate / "weights" / "last.pt"
        if ckpt.exists():
            last_ckpt = ckpt
            break

RESUME = last_ckpt is not None

if RESUME:
    print(f"\nLoading LibreYOLO26-nano from checkpoint: {last_ckpt} …")
    model = LibreYOLO26(model_path=str(last_ckpt), size="n", nb_classes=NC)
    # Extract project/name from the checkpoint dir so we resume in-place
    resume_project = str(last_ckpt.parents[2])
    resume_name = last_ckpt.parents[1].name
    print(f"Resuming into project={resume_project}, name={resume_name}")
else:
    print(f"\nInitializing LibreYOLO26-nano from scratch (nc={NC}) …")
    model = LibreYOLO26(model_path=None, size="n", nb_classes=NC)
    resume_project = "runs/train"
    resume_name = RUN_DIR_NAME


# ── Train ─────────────────────────────────────────────────────────────────────
status = "Resuming" if RESUME else "Starting"
print(f"\n{status} {EPOCHS}-epoch training on person class with bg_ratio={args.bg_ratio} (imgsz={IMGSZ}) …")
try:
    results = model.train(
        data=yaml_path,
        epochs=EPOCHS,
        batch=BATCH,
        imgsz=IMGSZ,
        device="0" if torch.cuda.is_available() else "cpu",
        workers=2,
        save_period=1,
        eval_interval=1,
        project=resume_project,
        name=resume_name,
        exist_ok=RESUME,
        resume=RESUME,
        cache='ram',
        
        # Explicit mosaic settings for optimal nano training
        mosaic_prob=1.0,
        no_aug_epochs=15,
    )
    print("\nTraining completed!")
    print(f"Results: {results}")

    for key, dest in [
        ("best_checkpoint", "yolo26_nano_person_silu_100ep_best.pt"),
        ("last_checkpoint", "yolo26_nano_person_silu_100ep_last.pt"),
    ]:
        if results and results.get(key):
            shutil.copy(results[key], dest)
            print(f"Saved {key} → {dest}")

except Exception as e:
    print(f"\nTraining failed:\n{e}")
    raise
